const express = require('express');
const db = require('./db');
const { authRequired, requireRole } = require('./auth');
const { genId } = require('./util');
const { createCase, syncAutomaticCases } = require('./curator-cases');

const router = express.Router(); router.use(authRequired);
const DAY=86400000, MAX_FOLLOWUP=14*DAY;
function branchIds(user) { return user.role==='admin' ? db.prepare('SELECT id FROM branches').all().map(x=>x.id) : db.prepare('SELECT branch_id id FROM curator_branches WHERE curator_id=?').all(user.id).map(x=>x.id); }
function allowedBranch(user,id){ return user.role==='admin'||branchIds(user).includes(id); }
function requireCurator(req,res,next){ if(!['curator','admin'].includes(req.user.role))return res.status(403).json({error:'Только для куратора'}); next(); }
function placeholders(items){ return items.map(()=>'?').join(','); }

router.get('/curator/admin/assignments', requireRole('admin'), (_req,res)=>res.json(db.prepare(`SELECT cb.curator_id,cb.branch_id,u.name curator_name,b.name branch_name FROM curator_branches cb JOIN users u ON u.id=cb.curator_id JOIN branches b ON b.id=cb.branch_id ORDER BY u.name,b.name`).all()));
router.put('/curator/admin/:id/branches', requireRole('admin'), (req,res)=>{
  const ids=[...new Set((req.body?.branchIds||[]).map(String))];
  if(!db.prepare("SELECT 1 FROM users WHERE id=? AND role='curator'").get(req.params.id))return res.status(400).json({error:'Пользователь не является куратором'});
  if(ids.some(id=>!db.prepare('SELECT 1 FROM branches WHERE id=?').get(id)))return res.status(400).json({error:'Один из филиалов не найден'});
  db.transaction(()=>{db.prepare('DELETE FROM curator_branches WHERE curator_id=?').run(req.params.id);const ins=db.prepare('INSERT INTO curator_branches(curator_id,branch_id,assigned_at) VALUES (?,?,?)');ids.forEach(id=>ins.run(req.params.id,id,Date.now()));})();
  res.json({curatorId:req.params.id,branchIds:ids});
});

router.get('/curator/bootstrap', requireCurator, (req,res)=>{
  const ids=branchIds(req.user); syncAutomaticCases(ids);
  if(!ids.length)return res.json({branches:[],stats:{students:0,groups:0,newCases:0,urgent:0}});
  const ph=placeholders(ids), branches=db.prepare(`SELECT * FROM branches WHERE id IN (${ph}) ORDER BY name`).all(...ids);
  res.json({branches,stats:{students:db.prepare(`SELECT COUNT(*) n FROM students_crm WHERE branch_id IN (${ph}) AND status='active'`).get(...ids).n,groups:db.prepare(`SELECT COUNT(*) n FROM groups WHERE branch_id IN (${ph}) AND status='active'`).get(...ids).n,newCases:db.prepare(`SELECT COUNT(*) n FROM curator_cases WHERE branch_id IN (${ph}) AND status='new'`).get(...ids).n,urgent:db.prepare(`SELECT COUNT(*) n FROM curator_cases WHERE branch_id IN (${ph}) AND status<>'resolved' AND next_contact_at IS NOT NULL AND next_contact_at<=?`).get(...ids,Date.now()+DAY).n}});
});

router.get('/curator/groups', requireCurator, (req,res)=>{const ids=branchIds(req.user);if(!ids.length)return res.json([]);const ph=placeholders(ids);res.json(db.prepare(`SELECT g.*,b.name branch_name,t.name teacher_name,(SELECT COUNT(*) FROM group_members gm WHERE gm.group_id=g.id AND (gm.until IS NULL OR gm.until>=?)) member_count FROM groups g JOIN branches b ON b.id=g.branch_id LEFT JOIN users t ON t.id=g.teacher_id WHERE g.branch_id IN (${ph}) ORDER BY b.name,g.name`).all(Date.now(),...ids));});
router.get('/curator/calendar', requireCurator, (req,res)=>{
  const ids=branchIds(req.user);if(!ids.length)return res.json([]);const requested=String(req.query.branchId||'');const scope=requested?[requested]:ids;if(requested&&!allowedBranch(req.user,requested))return res.status(403).json({error:'Нет доступа'});
  const from=String(req.query.from||new Date(Date.now()-7*DAY).toISOString().slice(0,10)),to=String(req.query.to||new Date(Date.now()+7*DAY).toISOString().slice(0,10));
  const ph=placeholders(scope),groups=db.prepare(`SELECT g.*,b.name branch_name,t.name teacher_name FROM groups g JOIN branches b ON b.id=g.branch_id LEFT JOIN users t ON t.id=g.teacher_id WHERE g.branch_id IN (${ph}) AND g.status='active'`).all(...scope);
  const events=[];for(const g of groups){const schedules=db.prepare('SELECT * FROM group_schedule WHERE group_id=?').all(g.id);for(let d=new Date(from+'T00:00:00Z'),end=new Date(to+'T00:00:00Z');d<=end;d=new Date(d.getTime()+DAY)){for(const s of schedules){if(d.getUTCDay()!==s.weekday)continue;const ymd=d.toISOString().slice(0,10),[hh,mm]=s.start_time.split(':').map(Number),at=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),hh,mm);const session=db.prepare("SELECT id,date,topic,conducted_by FROM lesson_sessions WHERE group_id=? AND substr(datetime(CAST(date AS INTEGER)/1000,'unixepoch'),1,10)=? ORDER BY created_at DESC LIMIT 1").get(g.id,ymd);const unmarked=!session&&at+s.duration_min*60000<Date.now();events.push({date:ymd,at,startTime:s.start_time,durationMin:s.duration_min,groupId:g.id,groupName:g.name,branchId:g.branch_id,branchName:g.branch_name,teacherName:g.teacher_name||'',lessonKind:g.lesson_kind,sessionId:session?.id||null,marked:!!session,unmarked});if(unmarked){for(const uid of require('./curator-cases').curatorIds(g.branch_id)){db.prepare(`INSERT OR IGNORE INTO notifications(id,user_id,type,text,link,channel,read,created_at) VALUES (?,?, 'unmarked_lesson', ?, '/curator/index.html#lessons','in_app',0,?)`).run(`unmarked_${g.id}_${ymd}_${uid}`,uid,`Преподаватель не отметил занятие «${g.name}» за ${ymd}`,Date.now());}}}}}
  res.json(events.sort((a,b)=>a.at-b.at));
});
router.get('/curator/students', requireCurator, (req,res)=>{const ids=branchIds(req.user);if(!ids.length)return res.json([]);const ph=placeholders(ids);res.json(db.prepare(`SELECT sc.*,u.avatar_url,u.age,b.name branch_name,(SELECT GROUP_CONCAT(g.name,', ') FROM group_members gm JOIN groups g ON g.id=gm.group_id WHERE gm.student_id=sc.user_id AND (gm.until IS NULL OR gm.until>=?)) groups FROM students_crm sc JOIN users u ON u.id=sc.user_id LEFT JOIN branches b ON b.id=sc.branch_id WHERE sc.branch_id IN (${ph}) ORDER BY sc.full_name`).all(Date.now(),...ids));});

router.get('/curator/students/:id', requireCurator, (req,res)=>{
  const s=db.prepare(`SELECT sc.*,u.avatar_url,u.age,u.login,b.name branch_name,t.name tariff_name FROM students_crm sc JOIN users u ON u.id=sc.user_id LEFT JOIN branches b ON b.id=sc.branch_id LEFT JOIN tariffs t ON t.id=sc.tariff_id WHERE sc.user_id=?`).get(req.params.id);
  if(!s||!allowedBranch(req.user,s.branch_id))return res.status(404).json({error:'Студент не найден'});
  const groups=db.prepare(`SELECT g.id,g.name,g.lesson_kind,t.name teacher_name FROM group_members gm JOIN groups g ON g.id=gm.group_id LEFT JOIN users t ON t.id=g.teacher_id WHERE gm.student_id=? AND (gm.until IS NULL OR gm.until>=?) ORDER BY g.name`).all(req.params.id,Date.now());
  const schedules=db.prepare(`SELECT gs.*,g.name group_name FROM group_schedule gs JOIN groups g ON g.id=gs.group_id JOIN group_members gm ON gm.group_id=g.id WHERE gm.student_id=? AND (gm.until IS NULL OR gm.until>=?) ORDER BY gs.weekday,gs.start_time`).all(req.params.id,Date.now());
  const attendance=db.prepare(`SELECT a.status,a.reason,ls.date,ls.topic,g.name group_name,sa.class_score,sa.homework_score,sa.homework_status,sa.engagement,sa.difficulty,sa.interest,sa.private_comment FROM attendance a JOIN lesson_sessions ls ON ls.id=a.lesson_session_id JOIN groups g ON g.id=ls.group_id LEFT JOIN student_assessments sa ON sa.lesson_session_id=ls.id AND sa.student_id=a.student_id WHERE a.student_id=? ORDER BY ls.date DESC LIMIT 90`).all(req.params.id);
  const attended=attendance.filter(x=>['present','late'].includes(x.status)).length;
  const payments=db.prepare('SELECT amount,currency,method,status,paid_at FROM subscription_payments WHERE student_id=? ORDER BY paid_at DESC').all(req.params.id);
  const feedback=db.prepare(`SELECT f.text,f.type,f.created_at,u.name teacher_name FROM feedback f LEFT JOIN users u ON u.id=f.teacher_id WHERE f.student_id=? ORDER BY f.created_at DESC LIMIT 30`).all(req.params.id);
  res.json({student:s,groups,schedules,attendance,attendancePercent:attendance.length?Math.round(attended*100/attendance.length):0,payments,feedback});
});

router.get('/curator/cases', requireCurator, (req,res)=>{const ids=branchIds(req.user);if(!ids.length)return res.json([]);syncAutomaticCases(ids);const ph=placeholders(ids);res.json(db.prepare(`SELECT cc.*,sc.full_name,sc.parent_phone,sc.parent_name,b.name branch_name,u.name curator_name,(SELECT comment FROM curator_case_events ce WHERE ce.case_id=cc.id ORDER BY ce.created_at DESC LIMIT 1) last_comment FROM curator_cases cc JOIN students_crm sc ON sc.user_id=cc.student_id JOIN branches b ON b.id=cc.branch_id LEFT JOIN users u ON u.id=cc.taken_by WHERE cc.branch_id IN (${ph}) ORDER BY CASE cc.status WHEN 'in_progress' THEN 0 WHEN 'new' THEN 1 WHEN 'follow_up' THEN 2 ELSE 3 END,cc.created_at DESC`).all(...ids));});
router.post('/curator/cases', requireCurator, (req,res)=>{const studentId=String(req.body?.studentId||''),category=String(req.body?.category||'');if(!['debtor','at_risk','absence'].includes(category))return res.status(400).json({error:'Некорректная категория'});const s=db.prepare('SELECT branch_id FROM students_crm WHERE user_id=?').get(studentId);if(!s||!allowedBranch(req.user,s.branch_id))return res.status(403).json({error:'Нет доступа'});res.status(201).json(createCase({studentId,category,description:req.body?.description,source:'manual'}));});
router.post('/curator/cases/:id/take', requireCurator, (req,res)=>{const c=db.prepare('SELECT * FROM curator_cases WHERE id=?').get(req.params.id);if(!c||!allowedBranch(req.user,c.branch_id))return res.status(404).json({error:'Задача не найдена'});if(c.status!=='new'&&c.status!=='follow_up')return res.status(409).json({error:'Задача уже находится в работе'});const active=db.prepare("SELECT id FROM curator_cases WHERE taken_by=? AND status='in_progress'").get(req.user.id);if(active&&active.id!==c.id)return res.status(409).json({error:'Сначала завершите работу с текущим клиентом'});const now=Date.now();db.transaction(()=>{db.prepare("UPDATE curator_cases SET status='in_progress',taken_by=?,taken_at=COALESCE(taken_at,?),updated_at=? WHERE id=?").run(req.user.id,now,now,c.id);db.prepare('INSERT INTO curator_case_events(id,case_id,actor_id,action,comment,created_at) VALUES (?,?,?,?,?,?)').run(genId('ce'),c.id,req.user.id,'taken',String(req.body?.comment||'').trim()||null,now);})();res.json({ok:true});});
router.post('/curator/cases/:id/complete', requireCurator, (req,res)=>{const c=db.prepare('SELECT * FROM curator_cases WHERE id=?').get(req.params.id);if(!c||c.taken_by!==req.user.id||c.status!=='in_progress')return res.status(409).json({error:'Сначала возьмите эту задачу в работу'});const comment=String(req.body?.comment||'').trim();if(comment.length<5)return res.status(400).json({error:'Комментарий должен содержать минимум 5 символов'});const outcome=req.body?.outcome==='resolved'?'resolved':'follow_up';const next=Number(req.body?.nextContactAt||0);if(outcome==='follow_up'&&(!next||next<=Date.now()||next>Date.now()+MAX_FOLLOWUP))return res.status(400).json({error:'Следующая связь обязательна и должна быть в пределах 14 дней'});const now=Date.now();db.transaction(()=>{db.prepare('UPDATE curator_cases SET status=?,next_contact_at=?,resolved_at=?,updated_at=? WHERE id=?').run(outcome,outcome==='follow_up'?next:null,outcome==='resolved'?now:null,now,c.id);db.prepare('INSERT INTO curator_case_events(id,case_id,actor_id,action,comment,next_contact_at,created_at) VALUES (?,?,?,?,?,?,?)').run(genId('ce'),c.id,req.user.id,outcome,comment,outcome==='follow_up'?next:null,now);})();res.json({ok:true,status:outcome});});
router.get('/curator/cases/:id/events', requireCurator, (req,res)=>{const c=db.prepare('SELECT * FROM curator_cases WHERE id=?').get(req.params.id);if(!c||!allowedBranch(req.user,c.branch_id))return res.status(404).json({error:'Не найдено'});res.json(db.prepare(`SELECT ce.*,u.name actor_name FROM curator_case_events ce JOIN users u ON u.id=ce.actor_id WHERE ce.case_id=? ORDER BY ce.created_at DESC`).all(c.id));});

router.get('/curator/homework', requireCurator, (req,res)=>{const ids=branchIds(req.user);if(!ids.length)return res.json([]);const ph=placeholders(ids);const rows=db.prepare(`SELECT ha.id assignment_id,ha.status,ha.submitted_at,ha.checked_at,ha.score,h.id homework_id,h.kind,h.assignment_text,h.attachment_url,h.due_date,h.created_at,ls.date lesson_date,g.id group_id,g.name group_name,g.branch_id,u.id student_id,u.name student_name,t.name teacher_name,sa.class_score,sa.homework_score,sa.homework_status,sa.private_comment,sa.updated_at assessment_updated_at FROM homework_assignments ha JOIN homework h ON h.id=ha.homework_id JOIN lesson_sessions ls ON ls.id=h.lesson_session_id JOIN groups g ON g.id=ls.group_id JOIN users u ON u.id=ha.student_id LEFT JOIN users t ON t.id=g.teacher_id LEFT JOIN student_assessments sa ON sa.lesson_session_id=ls.id AND sa.student_id=ha.student_id WHERE g.branch_id IN (${ph}) ORDER BY COALESCE(ha.submitted_at,h.created_at) DESC,g.name,u.name`).all(...ids);for(const row of rows.filter(x=>x.homework_status==='checking'&&x.assessment_updated_at<Date.now()-2*DAY)){for(const uid of require('./curator-cases').curatorIds(row.branch_id)){db.prepare(`INSERT OR IGNORE INTO notifications(id,user_id,type,text,link,channel,read,created_at) VALUES (?,?, 'homework_overdue', ?, '/curator/index.html#homework','in_app',0,?)`).run(`hw_overdue_${row.assignment_id}_${uid}`,uid,`ДЗ ${row.student_name} не проверено более двух дней`,Date.now());}}res.json(rows);});

router.post('/student-assessments', (req,res)=>{
  if(!['admin','teacher','assistant'].includes(req.user.role))return res.status(403).json({error:'Оценки выставляет преподаватель'});
  const lessonSessionId=String(req.body?.lessonSessionId||''),records=Array.isArray(req.body?.records)?req.body.records:[];
  const session=db.prepare('SELECT ls.group_id,g.teacher_id,g.assistant_id FROM lesson_sessions ls JOIN groups g ON g.id=ls.group_id WHERE ls.id=?').get(lessonSessionId);
  if(!session)return res.status(404).json({error:'Занятие не найдено'});if(req.user.role!=='admin'&&![session.teacher_id,session.assistant_id].includes(req.user.id))return res.status(403).json({error:'Это не ваша группа'});
  const score=v=>v==null||v===''?null:Number(v);for(const r of records){if(!r.studentId||[score(r.classScore),score(r.homeworkScore)].some(v=>v!==null&&(!Number.isInteger(v)||v<1||v>5)))return res.status(400).json({error:'Оценки должны быть от 1 до 5'});}
  const up=db.prepare(`INSERT INTO student_assessments(lesson_session_id,student_id,class_score,homework_score,homework_status,engagement,difficulty,interest,private_comment,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(lesson_session_id,student_id) DO UPDATE SET class_score=excluded.class_score,homework_score=excluded.homework_score,homework_status=excluded.homework_status,engagement=excluded.engagement,difficulty=excluded.difficulty,interest=excluded.interest,private_comment=excluded.private_comment,updated_by=excluded.updated_by,updated_at=excluded.updated_at`);
  db.transaction(()=>records.forEach(r=>up.run(lessonSessionId,r.studentId,score(r.classScore),score(r.homeworkScore),r.homeworkStatus||'none',r.engagement||null,r.difficulty||null,r.interest||null,String(r.privateComment||'').trim()||null,req.user.id,Date.now())))();
  for(const r of records){if((score(r.classScore)!==null&&score(r.classScore)<=2)||(score(r.homeworkScore)!==null&&score(r.homeworkScore)<=2)||r.interest==='not_interested')createCase({studentId:r.studentId,category:'at_risk',description:'Низкая оценка или потеря интереса по отметке преподавателя',source:'assessment'});}
  res.json({ok:true,updated:records.length});
});

router.get('/curator/reports/:type', requireCurator, (req,res)=>{const ids=branchIds(req.user);if(!ids.length)return res.json([]);const requested=req.query.branchId;if(requested&&!allowedBranch(req.user,requested))return res.status(403).json({error:'Нет доступа к филиалу'});const scope=requested?[requested]:ids,ph=placeholders(scope);if(req.params.type==='attendance')return res.json(db.prepare(`SELECT b.name branch,g.name group_name,sc.full_name,COUNT(a.id) total,SUM(CASE WHEN a.status IN ('present','late') THEN 1 ELSE 0 END) attended,ROUND(100.0*SUM(CASE WHEN a.status IN ('present','late') THEN 1 ELSE 0 END)/NULLIF(COUNT(a.id),0),1) attendance_percent FROM attendance a JOIN users u ON u.id=a.student_id JOIN students_crm sc ON sc.user_id=u.id JOIN lesson_sessions ls ON ls.id=a.lesson_session_id JOIN groups g ON g.id=ls.group_id JOIN branches b ON b.id=g.branch_id WHERE g.branch_id IN (${ph}) GROUP BY g.id,sc.user_id ORDER BY b.name,g.name,sc.full_name`).all(...scope));if(req.params.type==='performance')return res.json(db.prepare(`SELECT b.name branch,g.name group_name,sc.full_name,ROUND(AVG(sa.class_score),2) class_average,ROUND(AVG(sa.homework_score),2) homework_average,COUNT(sa.lesson_session_id) graded_lessons FROM student_assessments sa JOIN students_crm sc ON sc.user_id=sa.student_id JOIN lesson_sessions ls ON ls.id=sa.lesson_session_id JOIN groups g ON g.id=ls.group_id JOIN branches b ON b.id=g.branch_id WHERE g.branch_id IN (${ph}) GROUP BY g.id,sc.user_id ORDER BY b.name,g.name,sc.full_name`).all(...scope));res.status(404).json({error:'Неизвестный отчёт'});});

module.exports=router;
