const express=require('express');
const db=require('./db');
const {authRequired}=require('./auth');
const {genId}=require('./util');
const router=express.Router();
const normalizePhone=value=>String(value||'').replace(/\D/g,'').replace(/^8(?=\d{10}$)/,'7');
const configured=()=>!!(process.env.SIPUNI_WEBHOOK_TOKEN&&process.env.SIPUNI_CALL_URL_TEMPLATE);
function safeTemplateUrl(template,phone,extension){const raw=String(template||'').replaceAll('{phone}',encodeURIComponent(phone)).replaceAll('{extension}',encodeURIComponent(extension||''));const url=new URL(raw);if(url.protocol!=='https:'||!/(^|\.)sipuni\.com$/i.test(url.hostname))throw new Error('Шаблон звонка должен вести на HTTPS-домен sipuni.com');return url.toString()}
function eventTime(value){const n=Number(value);return n?(n<1e12?n*1000:n):Date.now()}

router.all('/events/:token',(req,res)=>{
  if(!process.env.SIPUNI_WEBHOOK_TOKEN||req.params.token!==process.env.SIPUNI_WEBHOOK_TOKEN)return res.status(404).json({success:false});
  const p={...req.query,...req.body},event=Number(p.event),callId=String(p.call_id||'').trim();
  if(!callId||![1,2,3,4].includes(event))return res.status(400).json({success:false});
  const external=normalizePhone(p.src_type==='1'?p.src_num:p.dst_type==='1'?p.dst_num:(p.src_num||p.dst_num));
  const extension=String(p.short_src_num||p.short_dst_num||'').trim();
  let row=db.prepare('SELECT * FROM sipuni_calls WHERE call_id=?').get(callId);
  if(!row){row=db.prepare('SELECT * FROM sipuni_calls WHERE call_id IS NULL AND phone=? AND created_at>? ORDER BY created_at DESC LIMIT 1').get(external,Date.now()-30*60*1000);if(row)db.prepare('UPDATE sipuni_calls SET call_id=?,updated_at=? WHERE id=?').run(callId,Date.now(),row.id);else{const curator=db.prepare("SELECT id FROM users WHERE role='curator' AND sipuni_extension=?").get(extension);const student=db.prepare('SELECT user_id,parent_phone FROM students_crm WHERE parent_phone IS NOT NULL').all().find(x=>normalizePhone(x.parent_phone).endsWith(external.slice(-10)));const id=genId('call'),now=Date.now();db.prepare('INSERT INTO sipuni_calls(id,call_id,student_id,curator_id,phone,extension,direction,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id,callId,student?.user_id||null,curator?.id||null,external,extension,p.src_type==='1'?'incoming':'outgoing','ringing',now,now);row={id}}}
  const now=Date.now();if(event===1)db.prepare("UPDATE sipuni_calls SET status='ringing',started_at=COALESCE(started_at,?),updated_at=? WHERE id=?").run(eventTime(p.timestamp),now,row.id);if(event===3)db.prepare("UPDATE sipuni_calls SET status='answered',answered_at=COALESCE(answered_at,?),updated_at=? WHERE id=?").run(eventTime(p.timestamp),now,row.id);if(event===2||event===4){const started=eventTime(p.call_start_timestamp||p.timestamp),answered=Number(p.call_answer_timestamp)?eventTime(p.call_answer_timestamp):null,ended=eventTime(p.timestamp),status=p.status==='ANSWER'?'completed':p.status==='NOANSWER'?'no_answer':p.status==='BUSY'?'busy':'failed';db.prepare('UPDATE sipuni_calls SET status=?,started_at=COALESCE(started_at,?),answered_at=COALESCE(answered_at,?),ended_at=?,duration_sec=?,recording_url=COALESCE(?,recording_url),raw_status=?,updated_at=? WHERE id=?').run(status,started,answered,ended,answered?Math.max(0,Math.round((ended-answered)/1000)):0,p.call_record_link||null,String(p.status||''),now,row.id)}
  res.json({success:true});
});

router.use(authRequired);
router.get('/status',(req,res)=>{const extension=db.prepare('SELECT sipuni_extension FROM users WHERE id=?').get(req.user.id)?.sipuni_extension||null;res.json({configured:configured(),hasWebhookToken:!!process.env.SIPUNI_WEBHOOK_TOKEN,hasCallTemplate:!!process.env.SIPUNI_CALL_URL_TEMPLATE,extension,webhookUrl:process.env.APP_ORIGIN?`${process.env.APP_ORIGIN.split(',')[0]}/api/sipuni/events/<SIPUNI_WEBHOOK_TOKEN>`:null})});
router.post('/cases/:id/call',async(req,res)=>{if(!['curator','admin'].includes(req.user.role))return res.status(403).json({error:'Только для куратора'});if(!configured())return res.status(503).json({error:'Sipuni ещё не настроен администратором'});const c=db.prepare('SELECT cc.*,sc.parent_phone FROM curator_cases cc JOIN students_crm sc ON sc.user_id=cc.student_id WHERE cc.id=?').get(req.params.id);if(!c)return res.status(404).json({error:'Задача не найдена'});if(req.user.role==='curator'&&(c.taken_by!==req.user.id||c.status!=='in_progress'))return res.status(409).json({error:'Сначала возьмите клиента в работу'});const phone=normalizePhone(c.parent_phone),extension=String(db.prepare('SELECT sipuni_extension FROM users WHERE id=?').get(req.user.id)?.sipuni_extension||'').trim();if(phone.length<10)return res.status(400).json({error:'У родителя не указан корректный телефон'});if(!extension)return res.status(400).json({error:'Администратор не указал ваш внутренний номер Sipuni'});const id=genId('call'),now=Date.now();db.prepare('INSERT INTO sipuni_calls(id,case_id,student_id,curator_id,phone,extension,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,c.id,c.student_id,req.user.id,phone,extension,'requested',now,now);try{const response=await fetch(safeTemplateUrl(process.env.SIPUNI_CALL_URL_TEMPLATE,phone,extension),{signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error('Sipuni ответил '+response.status);res.status(202).json({id,status:'requested',phoneMasked:'•••'+phone.slice(-4)})}catch(e){db.prepare("UPDATE sipuni_calls SET status='request_failed',raw_status=?,updated_at=? WHERE id=?").run(e.message,Date.now(),id);res.status(502).json({error:'Не удалось заказать звонок в Sipuni: '+e.message})}});
router.get('/cases/:id/calls',(req,res)=>{if(!['curator','admin'].includes(req.user.role))return res.status(403).json({error:'Нет доступа'});res.json(db.prepare('SELECT id,status,started_at,answered_at,ended_at,duration_sec,recording_url,raw_status,created_at FROM sipuni_calls WHERE case_id=? ORDER BY created_at DESC LIMIT 100').all(req.params.id))});
module.exports=router;
